version: '2'
services:
  geeksplaza:
    build: .
    ports:
      - "18080:8080"
      - "18787:8787"
    depends_on:
      - geeksplaza-db

  geeksplaza-db:
    image: postgres
    container_name: geeksplazadb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: geeksplaza
